apache/geaflow

.github/ISSUE_TEMPLATE/bug_report.md

When I wanted to create an issue, I found that only the feature-request template was available
According to the information, it is found that the templates (bug-report and custom) has the same name
So it was renamed based on https://github.com/TuGraph-family/tugraph-analytics/commit/f69aa453120890ae42acf487d739f6602f2ce1a7

[MINOR] Fix issue template name

---

geaflow/geaflow-common/src/main/java/com/antgroup/geaflow/common/binary/BinaryString.java
geaflow/geaflow-dsl/geaflow-dsl-plan/src/main/java/com/antgroup/geaflow/dsl/udf/table/string/IndexOf.java
geaflow/geaflow-dsl/geaflow-dsl-plan/src/main/java/com/antgroup/geaflow/dsl/udf/table/string/Instr.java
geaflow/geaflow-dsl/geaflow-dsl-plan/src/test/java/com/antgroup/geaflow/dsl/udf/string/UDFInstrTest.java
geaflow/geaflow-dsl/geaflow-dsl-plan/src/test/java/com/antgroup/geaflow/dsl/udf/string/UDFStringTest.java

Implemented the indexOf function in BinaryString by referencing spark UTF8String. Instr/IndexOf support BinaryString as input parameter.

[#20]Instr/IndexOf support BinaryString as input parameter

---

geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-kafka/src/main/java/com/antgroup/geaflow/dsl/connector/kafka/KafkaTableSource.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/test/resources/query/kafka_scan_001.sql

KafkaTableSource invoke DateTimeUtil.toUnixTime code，The first parameter uses format, and the second parameter is startTimeStr，The parameter order is reversed. This pr fix the bug.

[ISSUE-48] Fix kafka start time parse exception

---

geaflow/geaflow-common/src/main/java/com/antgroup/geaflow/common/utils/ReflectionUtil.java
geaflow/geaflow-core/geaflow-runtime/geaflow-runtime-core/src/main/java/com/antgroup/geaflow/runtime/core/scheduler/context/AbstractCycleSchedulerContext.java
geaflow/geaflow-core/geaflow-runtime/geaflow-runtime-core/src/main/java/com/antgroup/geaflow/runtime/core/scheduler/context/CheckpointSchedulerContext.java
geaflow/geaflow-core/geaflow-runtime/geaflow-runtime-core/src/main/java/com/antgroup/geaflow/runtime/core/scheduler/context/CycleSchedulerContextFactory.java
geaflow/geaflow-core/geaflow-runtime/geaflow-runtime-core/src/main/java/com/antgroup/geaflow/runtime/core/scheduler/context/RedoSchedulerContext.java
geaflow/geaflow-core/geaflow-runtime/geaflow-runtime-core/src/test/java/com/antgroup/geaflow/runtime/core/scheduler/ExecutionGraphCycleSchedulerTest.java
geaflow/geaflow-core/geaflow-runtime/geaflow-runtime-core/src/test/java/com/antgroup/geaflow/runtime/core/scheduler/PipelineCycleSchedulerTest.java
geaflow/geaflow-core/geaflow-runtime/geaflow-runtime-core/src/test/java/com/antgroup/geaflow/runtime/core/scheduler/context/AbstractCycleSchedulerContextTest.java

Aggregation statements in dynamic graphs save their state in DFS. An error occurs when restarting the graph after it has stopped. The issue has been identified as the lack of rollback support for the Agg operator. The Agg operator needs to support rollback. This pr is to support aggregate operator rollback in the dynamic graph.

[ISSUE-96] Support aggregate operator rollback in the dynamic graph

---

geaflow/geaflow-core/geaflow-engine/geaflow-shuffle/src/main/java/com/antgroup/geaflow/shuffle/api/pipeline/buffer/AbstractBuffer.java
geaflow/geaflow-core/geaflow-engine/geaflow-shuffle/src/main/java/com/antgroup/geaflow/shuffle/api/pipeline/buffer/HeapBuffer.java
geaflow/geaflow-core/geaflow-engine/geaflow-shuffle/src/main/java/com/antgroup/geaflow/shuffle/api/pipeline/buffer/PipeBuffer.java
geaflow/geaflow-core/geaflow-engine/geaflow-shuffle/src/main/java/com/antgroup/geaflow/shuffle/api/writer/ShardBuffer.java
geaflow/geaflow-core/geaflow-engine/geaflow-shuffle/src/main/java/com/antgroup/geaflow/shuffle/memory/ShuffleMemoryTracker.java
geaflow/geaflow-core/geaflow-engine/geaflow-shuffle/src/main/java/com/antgroup/geaflow/shuffle/service/ShuffleManager.java
geaflow/geaflow-core/geaflow-engine/geaflow-shuffle/src/test/java/com/antgroup/geaflow/shuffle/api/pipeline/fetcher/OneShardFetcherTest.java
geaflow/geaflow-core/geaflow-engine/geaflow-shuffle/src/test/java/com/antgroup/geaflow/shuffle/api/writer/SpillableShardBufferTest.java
geaflow/geaflow-core/geaflow-engine/geaflow-shuffle/src/test/java/com/antgroup/geaflow/shuffle/memory/ShuffleMemoryTrackerTest.java
geaflow/geaflow-core/geaflow-runtime/geaflow-runtime-core/src/test/java/com/antgroup/geaflow/runtime/core/scheduler/PipelineCycleSchedulerTest.java

‒ 在 Shuffle 组件中，ShuffleMemoryTracker 用来追踪 Shuffle 模块使用的内存量，通过 require 申请内存用量，通过 release 释放内存用量。
‒ 目前，在 Shuffle write 端有 require，使用完有 release，但是在 shuffle read 端没有 require，release 会导致内存使用量为负值。
In the Shuffle component, ShuffleMemoryTracker is used to track the amount of memory used by the Shuffle module, which can be requested using "require" and released using "release".
Currently, there is a "require" and "release" in the Shuffle write end, but there is no "require" in the Shuffle read end. Releasing memory without requiring it will result in a negative memory usage value.
当前的 require 行为在 ShardBuffer，release 行为在 OutBuffer，修改为统一在 OutBuffer 内存进行 require 和 release，可以保证初始化时有 require，关闭时有 release。
The current "require" behavior is in ShardBuffer, and the "release" behavior is in OutBuffer. …

[ISSUE-100] fix shuffle memory tracker log

---

geaflow/geaflow-common/src/main/java/com/antgroup/geaflow/common/config/keys/ExecutionConfigKeys.java
geaflow/geaflow-metrics/geaflow-stats-metrics/src/main/java/com/antgroup/geaflow/stats/sink/AsyncKvStoreWriter.java

当前 AsyncKvStoreWriter 默认启动 2 个异步线程 flush metric，但是由于在计算 sleep gap 时有 bug，会导致计算出负值，形成 while true 循环，导致 2 个线程占用过多的 CPU。
The current AsyncKvStoreWriter starts two asynchronous threads by default to flush metric. However, due to a bug in calculating the sleep gap, negative values may be computed, which leads to an infinite while-true loop and causes the two threads to consume too much CPU.
‒ flush 之后强制 sleep，不再占用 CPU 资源
‒ 将 flush 线程数改为 1 个
‒ 将 flush interval 改为 1s
- Force sleep after flush to release CPU resources.
- Change the number of flush threads to 1.
- Change the flush interval to 1 second.

[ISSUE-98] fix async state writer bug

---

geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/engine/GeaFlowAlgorithmDynamicTraversalFunction.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/engine/GeaFlowAlgorithmTraversalFunction.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/traversal/operator/MatchVertexOperator.java

In dynamic graph algorithms, the process() method is called without considering whether the vertices exist. If a vertex has not yet been inserted into the graph and is accessed, it will cause an NPE (NullPointerException), such as when accessing the endpoint of an edge. It is necessary to add null check logic to skip the target vertex that is null.

[ISSUE-139] Fix  NPE for UDGA when the target vertex  is not exist

---

geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-jdbc/src/main/java/com/antgroup/geaflow/dsl/connector/jdbc/JDBCTableSink.java
geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-jdbc/src/test/java/com/antgroup/geaflow/dsl/connector/jdbc/JDBCTableConnectorTest.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/test/java/com/antgroup/geaflow/dsl/runtime/query/JDBCTest.java

After using the JDBC Connector to connect to MYSQL for writing, the job runs successfully but the data is not written to the database. The reason is that the Sink implementation creates a temporary table, causing the data to be written into the temporary table.

[ISSUE-158] JDBC connector cannot write data into mysql database

---

geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/engine/GeaFlowRuntimeTable.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/test/resources/query/project_006.sql

For sink table with primary key, e.g. mysql, we need do data shuffle by the primary key before write data to the sink table.
If not do this,  write conflict will happen on the same primary key when  different task update data to the same key.

[ISSUE-164] Add keyby for sink table with primary key

---

geaflow/geaflow-dsl/geaflow-dsl-plan/src/main/java/com/antgroup/geaflow/dsl/planner/GQLContext.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/command/CreateGraphCommand.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/engine/AbstractTraversalRuntimeContext.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/engine/GeaFlowAlgorithmAggTraversal.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/engine/GeaFlowAlgorithmAggTraversalFunction.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/engine/GeaFlowAlgorithmDynamicAggTraversal.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/engine/GeaFlowAlgorithmDynamicAggTraversalFunction.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/engine/GeaFlowAlgorithmDynamicRuntimeContext.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/engine/GeaFlowAlgorithmRuntimeContext.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/engine/GeaFlowDynamicTraversalRuntimeContext.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/engine/GeaFlowDynamicVCAggTraversal.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/engine/GeaFlowDynamicVCAggTraversalFunction.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/engine/GeaFlowKVAlgorithmAggregateFunction.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/engine/GeaFlowKVTraversalAggregateFunction.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/engine/GeaFlowRuntimeGraph.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/engine/GeaFlowStaticTraversalRuntimeContext.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/engine/GeaFlowStaticVCAggTraversal.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/engine/GeaFlowStaticVCAggTraversalFunction.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/plan/PhysicGraphScanRelNode.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/traversal/DagTopologyGroup.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/traversal/ExecuteDagGroupImpl.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/traversal/TraversalRuntimeContext.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/traversal/message/ITraversalAgg.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/traversal/message/KVTraversalAgg.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/traversal/operator/AbstractStepOperator.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/traversal/operator/StepLoopUntilOperator.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/traversal/operator/StepOperator.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/util/QueryUtil.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/test/java/com/antgroup/geaflow/dsl/runtime/query/KafkaFoTest.java

提前结束ISSUE-#167已经合并，PR见https://github.com/TuGraph-family/tugraph-analytics/pull/168
The early termination ISSUE-https://github.com/TuGraph-family/tugraph-analytics/issues/167 has been merged, and the corresponding PR can be found at https://github.com/TuGraph-family/tugraph-analytics/pull/168.
现在需要在DSL Traversal and Algorithm 两种计算中支持提前结束，实现相应的AggregateFunction.
Now, it is required to support early termination in both DSL Traversal and Algorithm calculations, and implement the corresponding AggregateFunction.

[ISSUE-171] DSL Supports  early termination for Traversal and Algorithm execution

---

geaflow/geaflow-common/src/main/java/com/antgroup/geaflow/common/config/keys/DSLConfigKeys.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/QueryEngine.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/engine/GeaFlowQueryEngine.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/engine/GeaFlowRuntimeGraph.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/function/graph/source/AbstractVertexScanSourceFunction.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/function/graph/source/DynamicGraphVertexScanSourceFunction.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/function/graph/source/StaticGraphVertexScanSourceFunction.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/test/java/com/antgroup/geaflow/dsl/runtime/query/LdbcTest.java

Support converting traversal all vertices in the graph to traversal by stream execution. Traversal by stream can divide trigger points into several groups to reduce the number of trigger points in each group and lower the peak memory usage during execution. This can effectively reduce the possibility of GC or OOM, but the trade-off is that the runtime cost may increase rapidly.

[ISSUE-179] Support converting traversal all to traversal by stream

---

geaflow/geaflow-common/src/main/java/com/antgroup/geaflow/common/utils/FutureUtil.java
geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/container/Container.java
geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/rpc/IContainerEndpointRef.java
geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/rpc/RpcClient.java
geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/rpc/RpcResponseFuture.java
geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/rpc/impl/ContainerEndpointRef.java
geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/rpc/impl/PipelineMasterEndpointRef.java
geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/test/java/com/antgroup/geaflow/cluster/rpc/AsyncRpcTest.java
geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/test/resources/log4j.properties
geaflow/geaflow-core/geaflow-runtime/geaflow-runtime-core/src/main/java/com/antgroup/geaflow/runtime/core/scheduler/ExecutionGraphCycleScheduler.java
geaflow/geaflow-core/geaflow-runtime/geaflow-runtime-core/src/main/java/com/antgroup/geaflow/runtime/core/scheduler/PipelineCycleScheduler.java
geaflow/geaflow-core/geaflow-runtime/geaflow-runtime-core/src/test/java/com/antgroup/geaflow/runtime/core/scheduler/BaseCycleSchedulerTest.java

使用独立的rpc不能保证有序，在rpc server端可能接收到乱序，如果在一组rpc请求内，允许乱序，而不同组直接通过同步等待，保证严格有序即可。
在scheduler每一轮发送的一组event，对于发给单个worker的event，已经合并到ComposeEvent中，不同event是发给不同的worker的，也即这些event可以允许乱序，在运行时表现为不同worker收到event时间先后顺序不同而已。
当一组event发送完成后，同步等待所有event的响应，直到确认所有event的回应后，才继续执行。

[ISSUE-184] Support async submit events.

---

geaflow/geaflow-dsl/geaflow-dsl-catalog/src/main/java/com/antgroup/geaflow/dsl/schema/GeaFlowGraph.java
geaflow/geaflow-dsl/geaflow-dsl-common/src/main/java/com/antgroup/geaflow/dsl/common/exception/GeaFlowDSLException.java
geaflow/geaflow-dsl/geaflow-dsl-common/src/main/java/com/antgroup/geaflow/dsl/common/types/EdgeType.java
geaflow/geaflow-dsl/geaflow-dsl-common/src/main/java/com/antgroup/geaflow/dsl/common/types/VertexType.java
geaflow/geaflow-dsl/geaflow-dsl-parser/src/main/java/com/antgroup/geaflow/dsl/calcite/EdgeRecordType.java
geaflow/geaflow-dsl/geaflow-dsl-parser/src/main/java/com/antgroup/geaflow/dsl/calcite/GraphRecordType.java
geaflow/geaflow-dsl/geaflow-dsl-parser/src/main/java/com/antgroup/geaflow/dsl/calcite/VertexRecordType.java
geaflow/geaflow-dsl/geaflow-dsl-plan/src/main/java/com/antgroup/geaflow/dsl/schema/function/BuildInSqlFunctionTable.java
geaflow/geaflow-dsl/geaflow-dsl-plan/src/main/java/com/antgroup/geaflow/dsl/udf/table/other/EdgeSrcId.java
geaflow/geaflow-dsl/geaflow-dsl-plan/src/main/java/com/antgroup/geaflow/dsl/udf/table/other/EdgeTargetId.java
geaflow/geaflow-dsl/geaflow-dsl-plan/src/main/java/com/antgroup/geaflow/dsl/udf/table/other/EdgeTimestamp.java
geaflow/geaflow-dsl/geaflow-dsl-plan/src/main/java/com/antgroup/geaflow/dsl/udf/table/other/GraphMetaFieldAccessFunction.java
geaflow/geaflow-dsl/geaflow-dsl-plan/src/main/java/com/antgroup/geaflow/dsl/udf/table/other/VertexId.java
geaflow/geaflow-dsl/geaflow-dsl-plan/src/main/java/com/antgroup/geaflow/dsl/util/FunctionUtil.java
geaflow/geaflow-dsl/geaflow-dsl-plan/src/main/java/com/antgroup/geaflow/dsl/util/GraphSchemaUtil.java
geaflow/geaflow-dsl/geaflow-dsl-plan/src/test/java/com/antgroup/geaflow/dsl/GQLValidateGraphRecordTypeTest.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/util/SchemaUtil.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/test/java/com/antgroup/geaflow/dsl/runtime/query/GQLMatchTest.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/test/resources/expect/gql_match_012.txt
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/test/resources/query/gql_match_012.sql

Currently, due to the presence of the union operation, the constraint for the meta fields of graph vertices and edges is that all vertex IDs must have the same name, and all edge source, destination, and timestamps must have the same name. This constraint is clearly too strong, and it is necessary to support meta fields with different names.

[ISSUE-214] Support different names for vertex and edge meta fields 

---

build.sh
geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/clustermanager/AbstractClusterManager.java
geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/common/AbstractContainer.java
geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/heartbeat/HeartbeatClient.java
geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/heartbeat/HeartbeatManager.java
geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/heartbeat/HeartbeatSender.java
geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/rpc/IMasterEndpointRef.java
geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/rpc/RpcClient.java
geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/rpc/impl/MasterEndpoint.java
geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/rpc/impl/MasterEndpointRef.java
geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/test/java/com/antgroup/geaflow/cluster/rpc/RpcEndpointRefTest.java
geaflow/geaflow-core/geaflow-engine/geaflow-rpc-proto/src/main/java/com/antgroup/geaflow/rpc/proto/Master.java
geaflow/geaflow-core/geaflow-engine/geaflow-rpc-proto/src/main/java/com/antgroup/geaflow/rpc/proto/MasterServiceGrpc.java
geaflow/geaflow-core/geaflow-engine/geaflow-rpc-proto/src/main/proto/master.proto
geaflow/geaflow-deploy/docker/Dockerfile
geaflow/geaflow-deploy/docker/Dockerfile-arm64
geaflow/geaflow-deploy/docker/start-process.sh
geaflow/geaflow-deploy/geaflow-on-k8s/src/main/java/com/antgroup/geaflow/cluster/k8s/clustermanager/KubernetesResourceBuilder.java

* Drivers and containers now check and register heartbeat after failover of master.
* Add labels for k8s services and deployments.

[ISSUE-227] Drivers and containers check and register heartbeat after failover

---

geaflow-console/app/core/service/src/main/java/com/antgroup/geaflow/console/core/service/statement/AnalyticsClientFactory.java
geaflow-console/docker/bin/start-process.sh
geaflow/geaflow-examples/src/test/java/com/antgroup/geaflow/example/service/BaseServiceTest.java
geaflow/geaflow-plugins/geaflow-service-discovery/geaflow-service-discovery-redis/src/main/java/com/antgroup/geaflow/service/discovery/RedisServiceConsumer.java
geaflow/geaflow-plugins/geaflow-service-discovery/geaflow-service-discovery-redis/src/main/java/com/antgroup/geaflow/service/discovery/RedisServiceProvider.java
geaflow/geaflow-plugins/geaflow-service-discovery/geaflow-service-discovery-redis/src/test/java/com/antgroup/geaflow/service/discovery/RedisTest.java

In the latest version, the meta service does not rely on zookeeper, so delete the Zookeeper-related directory.

[ISSUE-326]Delete zookeeper directory

---

geaflow-kubernetes-operator/geaflow-kubernetes-operator-web/pom.xml
geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/client/callback/ClusterStartedCallback.java
geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/runner/CommandRunner.java
geaflow/geaflow-dashboard/pom.xml
geaflow/geaflow-deploy/geaflow-cluster-runner/src/main/java/com/antgroup/geaflow/cluster/runner/failover/AbstractFailoverStrategy.java
geaflow/geaflow-deploy/geaflow-cluster-runner/src/main/java/com/antgroup/geaflow/cluster/runner/failover/ClusterFailoverStrategy.java
geaflow/geaflow-deploy/geaflow-cluster-runner/src/main/java/com/antgroup/geaflow/cluster/runner/failover/DisableFailoverStrategy.java
geaflow/geaflow-deploy/geaflow-on-k8s/src/main/java/com/antgroup/geaflow/cluster/k8s/client/KubernetesClusterClient.java
geaflow/geaflow-deploy/geaflow-on-k8s/src/main/java/com/antgroup/geaflow/cluster/k8s/failover/KubernetesComponentFailoverStrategy.java
geaflow/geaflow-deploy/geaflow-on-k8s/src/main/java/com/antgroup/geaflow/cluster/k8s/handler/AbstractPodHandler.java
geaflow/geaflow-deploy/geaflow-on-k8s/src/main/java/com/antgroup/geaflow/cluster/k8s/handler/PodAddedHandler.java
geaflow/geaflow-deploy/geaflow-on-k8s/src/main/java/com/antgroup/geaflow/cluster/k8s/handler/PodDeletedHandler.java
geaflow/geaflow-deploy/geaflow-on-k8s/src/main/java/com/antgroup/geaflow/cluster/k8s/handler/PodEvent.java
geaflow/geaflow-deploy/geaflow-on-k8s/src/main/java/com/antgroup/geaflow/cluster/k8s/handler/PodEvictHandler.java
geaflow/geaflow-deploy/geaflow-on-k8s/src/main/java/com/antgroup/geaflow/cluster/k8s/handler/PodHandlerRegistry.java
geaflow/geaflow-deploy/geaflow-on-k8s/src/main/java/com/antgroup/geaflow/cluster/k8s/handler/PodOOMHandler.java
geaflow/geaflow-deploy/geaflow-on-k8s/src/main/java/com/antgroup/geaflow/cluster/k8s/utils/KubernetesUtils.java
geaflow/geaflow-deploy/geaflow-on-k8s/src/main/java/com/antgroup/geaflow/cluster/k8s/watcher/KubernetesPodWatcher.java
geaflow/geaflow-metrics/geaflow-stats-metrics/src/main/java/com/antgroup/geaflow/stats/collector/EventCollector.java
geaflow/geaflow-metrics/geaflow-stats-metrics/src/main/java/com/antgroup/geaflow/stats/collector/StatsCollectorFactory.java
geaflow/geaflow-metrics/geaflow-stats-metrics/src/main/java/com/antgroup/geaflow/stats/model/EventInfo.java
geaflow/geaflow-metrics/geaflow-stats-metrics/src/main/java/com/antgroup/geaflow/stats/model/EventLabel.java
geaflow/geaflow-metrics/geaflow-stats-metrics/src/main/java/com/antgroup/geaflow/stats/model/ExceptionInfo.java

[ISSUE-335] Support to report k8s events & nodejs source url fix

---

geaflow/geaflow-common/src/main/java/com/antgroup/geaflow/common/config/keys/ConnectorConfigKeys.java
geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-api/src/main/java/com/antgroup/geaflow/dsl/connector/api/serde/DeserializerFactory.java
geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-api/src/main/java/com/antgroup/geaflow/dsl/connector/api/serde/impl/JsonDeserializer.java
geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-api/src/main/java/com/antgroup/geaflow/dsl/connector/api/util/ConnectorConstants.java
geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-api/src/test/java/com/antgroup/geaflow/dsl/connector/api/JsonDeserializerTest.java
geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-hive/src/main/java/com/antgroup/geaflow/dsl/connector/hive/HiveTableSource.java
geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-jdbc/src/main/java/com/antgroup/geaflow/dsl/connector/jdbc/JDBCTableSource.java
geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-kafka/src/main/java/com/antgroup/geaflow/dsl/connector/kafka/KafkaTableSource.java
geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-kafka/src/test/java/com/antgroup/geaflow/dsl/connector/kafka/KafkaTableConnectorTest.java
geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-pulsar/src/main/java/com/antgroup/geaflow/dsl/connector/pulsar/PulsarTableSource.java
geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-socket/src/main/java/com/antgroup/geaflow/dsl/connector/socket/SocketTableSource.java

- new configuration for connector.format
- new JsonDeserializer extends TableDeserializer to deserialize string to row
- return JsonDeserializer according to configuration in Kafka Source

[ISSUE-344] Deserialize json in kafka source

---

README.md
README_cn.md
docs/docs-cn/source/3.quick_start/1.quick_start.md
docs/docs-cn/source/3.quick_start/2.quick_start_docker.md
docs/docs-en/source/3.quick_start/1.quick_start.md
docs/docs-en/source/3.quick_start/2.quick_start_docker.md

Optimize the Quick Start documentation to allow users to experience it more quickly #375 
According to the current Quick Start guide, users need to build the entire engine and console images to experience the demo case, which is time-consuming. To help users experience the Quick Start demo more quickly, the documentation should be optimized to specify that, when running demos that only rely on the engine JAR package, users only need to package the engine without building images. When running demos that rely on both the console image and the JAR package, users only need to build both.

 [ISSUE-375] Optimize the Quick Start documentation to allow users to experience it more quickly

---

geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-hive/pom.xml
geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-hive/src/main/java/com/antgroup/geaflow/dsl/connector/hive/adapter/Hive3Adapter.java
geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-hive/src/main/java/com/antgroup/geaflow/dsl/connector/hive/adapter/HiveVersionAdapters.java
geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-hive/src/test/java/com/antgroup/geaflow/dsl/connector/hive/BaseHiveTest.java

Support Hive 3.0.0 3.1.0 3.1.1 3.1.2
Change the hadoop and hive version in geaflow-dsl-connector-hive/pom.xml to 3.1.0 and 3.1.2
- [ ✔] Tests have Added for the changes
- [ x] Production environment verified

Support Hive 3.x

---

geaflow/geaflow-plugins/geaflow-file/geaflow-file-common/src/main/java/com/antgroup/geaflow/file/FileConfigKeys.java
geaflow/geaflow-plugins/geaflow-file/geaflow-file-common/src/main/java/com/antgroup/geaflow/file/PersistentType.java
geaflow/geaflow-plugins/geaflow-file/geaflow-file-s3/pom.xml
geaflow/geaflow-plugins/geaflow-file/geaflow-file-s3/src/main/java/com/antgroup/geaflow/file/s3/S3IO.java
geaflow/geaflow-plugins/geaflow-file/geaflow-file-s3/src/main/java/com/antgroup/geaflow/file/s3/S3InputStream.java
geaflow/geaflow-plugins/geaflow-file/geaflow-file-s3/src/main/resources/META-INF/services/com.antgroup.geaflow.file.IPersistentIO
geaflow/geaflow-plugins/geaflow-file/geaflow-file-s3/src/test/java/com/antgroup/geaflow/file/s3/S3IOTest.java
geaflow/geaflow-plugins/geaflow-file/geaflow-file-s3/src/test/resources/log4j.properties
geaflow/geaflow-plugins/geaflow-file/pom.xml
geaflow/pom.xml

Support S3 persistent IO type for tugraph-analytics.
- [✅ ] Tests have Added for the changes

[ISSUE-399] Support S3 persistent IO type

---

LICENSE

Minor change. The appendix is an example of how to apply the license to a file and should not have a specific copyright line.
N/A

Fix LICENSE copyright line

---

geaflow/geaflow-common/src/main/java/com/antgroup/geaflow/common/config/keys/ExecutionConfigKeys.java
geaflow/geaflow-common/src/main/java/com/antgroup/geaflow/common/thread/Executors.java
geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/clustermanager/AbstractClusterManager.java
geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/collector/EmitterService.java
geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/container/Container.java
geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/fetcher/FetcherService.java
geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/task/service/AbstractTaskService.java
geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/task/service/TaskService.java
geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/worker/DispatcherService.java
geaflow/geaflow-deploy/geaflow-on-local/src/main/java/com/antgroup/geaflow/cluster/local/clustermanager/LocalClusterManager.java

…ent (#547)
* Fix BRPC endpoint registration conflict when launching multiple containers in local mode
* Add geaflow.executor.thread.max.multiple configuration for thread pool scaling
Verification Steps:
1. Test local mode with multiple containers (geaflow.container.num=3):
- Expected: Fails with IllegalArgumentException "local mode containerNum must equal with 1"
2. Test with excessive worker threads (geaflow.container.worker.num=170):
- Expected: Fails with IllegalArgumentException "executor threads should be smaller than 60"
3. Test with proper config (geaflow.executor.thread.max.multiple=50):
- Expected: Runs successfully with completion message "source already finished"

[Cluster] Fix BRPC endpoint conflict in local multi-container deployment

---

geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-random/pom.xml
geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-random/src/main/java/com/antgroup/geaflow/dsl/connector/random/RandomSourceConfigKeys.java
geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-random/src/main/java/com/antgroup/geaflow/dsl/connector/random/RandomTableConnector.java
geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-random/src/main/java/com/antgroup/geaflow/dsl/connector/random/RandomTableSource.java
geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-random/src/main/resources/META-INF/services/com.antgroup.geaflow.dsl.connector.api.TableConnector
geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-random/src/test/java/com/antgroup/geaflow/dsl/connector/random/RandomTableConnectorTest.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/pom.xml
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/test/java/com/antgroup/geaflow/dsl/runtime/query/GQLInsertTest.java
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/test/resources/expect/gql_insert_and_graph_005.txt
geaflow/geaflow-dsl/geaflow-dsl-runtime/src/test/resources/query/gql_insert_and_graph_005.sql
geaflow/geaflow-dsl/pom.xml

Add random table source
example:
CREATE TABLE tbl_person (
id bigint,
name varchar,
age int
) WITH (
type='random',
`geaflow.dsl.window.size`=20,
`geaflow.dsl.random.source.tuples.per.second`=100.0,
`geaflow.dsl.random.source.max.batch`=100
);

Add random table source

---

geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/org/apache/geaflow/cluster/client/callback/JobOperatorCallback.java
geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/org/apache/geaflow/cluster/client/callback/RestJobOperatorCallback.java
geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/test/java/org/apache/geaflow/cluster/client/callback/RestJobOperatorCallbackTest.java

1. In [PR 531](https://github.com/apache/geaflow/pull/531), a callback mechanism upon task completion was introduced.
2. The callback request is implemented via a POST method, but an invalid body format in the POST request caused [ISSUE 581](https://github.com/apache/geaflow/issues/581).
3. This PR fixes the issue of invalid request body.
3.1 POST body before changes: `{"success":true,"data":{"params":{"action":"finish"}}}`
3.2 POST body after changes: `{"success":true,"action":"finish"}`
Closes #581

Fix callback issue when task done
