apache/geaflow

- README.md
- README_cn.md
- docs/docs-cn/application-development/dsl/overview.md
- docs/docs-en/application-development/dsl/overview.md
- docs/index.md
- docs/index_cn.md
- docs/requirements.in
- docs/requirements.txt
- mkdocs.yml
This PR supports rendering the documentation of TuGraph-Analytics to Readthedocs.
> Support rendering the docs on Readthedocs

- build.sh
- geaflow-console/Dockerfile-arm64
- geaflow-console/app/core/service/src/main/java/com/antgroup/geaflow/console/core/service/runtime/ContainerRuntime.java
- geaflow-console/pom.xml
- geaflow/geaflow-deploy/docker/Dockerfile-arm64
- geaflow/pom.xml
- pom.xml
1. add Dockerfile-arm for Geaflow image
2. update mysql version, reduce the size of the image: Geaflow-console-arm
- Tests have Added for the changes
> Support arm64 architecture docker image

- docs/docs-cn/quick_start.md
- docs/docs-cn/visualization/collaborate_with_g6vp.md
- docs/docs-en/quick_start.md
- docs/docs-en/visualization/collaborate_with_g6vp.md
Relative Issue: https://github.com/TuGraph-family/tugraph-analytics/issues/2
> docs: g6vp support to geaflow calculation visualization

- pom.xml
Remove duplicate property configuration in pom.xml to avoid conflicts.
> fix(pom): remove duplicate property configuration

- tools/checkstyle-suppressions.xml
- fixes: #33 
Local Test on Win10, it works:
```bash
[INFO] --- maven-javadoc-plugin:2.9.1:jar (default) @ geaflow-console-test ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for geaflow-parent 0.2-SNAPSHOT:
[INFO]
[INFO] geaflow-parent ..................................... SUCCESS [  3.179 s]
[INFO] geaflow ............................................ SUCCESS [  0.565 s]
[INFO] geaflow-common ..................................... SUCCESS [ 13.148 s]
[INFO] geaflow-model ...................................... SUCCESS [  6.054 s]
[INFO] geaflow-utils ...................................... SUCCESS [  5.605 s]
[INFO] geaflow-state ...................................... SUCCESS [  0.423 s]
[INFO] geaflow-state-common …
```
> [ISSUE-33] Fix compile on windows

- geaflow/geaflow-dsl/geaflow-dsl-common/src/main/java/com/antgroup/geaflow/dsl/common/compile/FunctionInfo.java
- geaflow/geaflow-dsl/geaflow-dsl-common/src/main/java/com/antgroup/geaflow/dsl/common/compile/QueryCompiler.java
- geaflow/geaflow-dsl/geaflow-dsl-parser/src/main/java/com/antgroup/geaflow/dsl/util/SqlNodeUtil.java
- geaflow/geaflow-dsl/geaflow-dsl-plan/src/main/java/com/antgroup/geaflow/dsl/planner/GQLContext.java
- geaflow/geaflow-dsl/geaflow-dsl-plan/src/main/java/com/antgroup/geaflow/dsl/planner/GQLOperatorTable.java
- geaflow/geaflow-dsl/geaflow-dsl-plan/src/test/java/com/antgroup/geaflow/dsl/planner/GQLContextTest.java
- geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/QueryClient.java
- geaflow/geaflow-dsl/geaflow-dsl-runtime/src/test/java/com/antgroup/geaflow/dsl/runtime/CompilerTest.java
> Support list unresolved functions

- docs/docs-cn/deploy/install_guide.md
- docs/docs-en/deploy/install_guide.md
- geaflow-console/app/bootstrap/src/main/resources/config/application.properties
- geaflow-console/docker/bin/start-process.sh
Issue: https://github.com/TuGraph-family/tugraph-analytics/issues/52
> Support config node/java process port

- geaflow-console/app/biz/shared/src/main/java/com/antgroup/geaflow/console/biz/shared/convert/GraphViewConverter.java
- geaflow-console/app/biz/shared/src/main/java/com/antgroup/geaflow/console/biz/shared/view/GraphView.java
- geaflow-console/app/common/dal/src/main/java/com/antgroup/geaflow/console/common/dal/entity/GraphEntity.java
- geaflow-console/app/core/model/src/main/java/com/antgroup/geaflow/console/core/model/data/GeaflowGraph.java
- geaflow-console/app/core/service/src/main/java/com/antgroup/geaflow/console/core/service/converter/GraphConverter.java
- geaflow/geaflow-dsl/geaflow-dsl-catalog/src/main/java/com/antgroup/geaflow/dsl/catalog/console/CatalogUtil.java
- geaflow/geaflow-dsl/geaflow-dsl-catalog/src/main/java/com/antgroup/geaflow/dsl/catalog/console/GraphModel.java
The column of static_graph does not created in console init file. Now remove static graph to fix.
> [ISSUE-63] Fix missing static_graph field exception when init console mysql database

- geaflow-console/app/common/util/src/main/java/com/antgroup/geaflow/console/common/util/FileUtil.java
- geaflow-console/app/common/util/src/main/java/com/antgroup/geaflow/console/common/util/ProcessUtil.java
- geaflow-console/app/core/model/src/main/java/com/antgroup/geaflow/console/core/model/plugin/config/ConsolePluginConfigClass.java
- geaflow-console/app/core/service/src/main/java/com/antgroup/geaflow/console/core/service/file/LocalFileClient.java
- geaflow-console/app/core/service/src/main/java/com/antgroup/geaflow/console/core/service/file/VersionFileFactory.java
- geaflow-console/app/core/service/src/main/java/com/antgroup/geaflow/console/core/service/runtime/ContainerRuntime.java
- geaflow-web/packages/app/client/src/components/@@plugins/src/components/console/geaflow/job-management/job-detail/components/JobOffSet.tsx
- geaflow/geaflow-dsl/geaflow-dsl-catalog/src/main/java/com/antgroup/geaflow/dsl/catalog/console/GeaFlowPluginType.java
Refrence: https://github.com/TuGraph-family/tugraph-analytics/issues/65
> Fix status to be finished when batch task completed

- geaflow/geaflow-dsl/geaflow-dsl-catalog/src/main/java/com/antgroup/geaflow/dsl/catalog/console/CatalogUtil.java
fix to obtain table/graph type from catalog config type.
> [ISSUE-69]Fix catalog plugin config 

- geaflow/geaflow-common/src/main/java/com/antgroup/geaflow/common/binary/BinaryString.java
- geaflow/geaflow-dsl/geaflow-dsl-plan/src/main/java/com/antgroup/geaflow/dsl/udf/table/string/Concat.java
- geaflow/geaflow-dsl/geaflow-dsl-plan/src/main/java/com/antgroup/geaflow/dsl/udf/table/string/ConcatWS.java
- geaflow/geaflow-dsl/geaflow-dsl-plan/src/test/java/com/antgroup/geaflow/dsl/udf/string/UDFStringTest.java
> [ISSUE-28] Concat/ConcatWs support BinaryString as input parameter

- geaflow/geaflow-plugins/geaflow-store/geaflow-store-rocksdb/pom.xml
> Fix Oss plugin not found when using oss as the graph storage

- geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-hbase/pom.xml
- geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-hbase/src/main/java/com/antgroup/geaflow/dsl/connector/hbase/HBaseConfigKeys.java
- geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-hbase/src/main/java/com/antgroup/geaflow/dsl/connector/hbase/HBaseConstants.java
- geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-hbase/src/main/java/com/antgroup/geaflow/dsl/connector/hbase/HBaseTableConnector.java
- geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-hbase/src/main/java/com/antgroup/geaflow/dsl/connector/hbase/HBaseTableSink.java
- geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-hbase/src/main/resources/META-INF/services/com.antgroup.geaflow.dsl.connector.api.TableConnector
- geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-hbase/src/test/java/com/antgroup/geaflow/dsl/connector/hbase/HBaseConnectorTest.java
- geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-hbase/src/test/java/com/antgroup/geaflow/dsl/connector/hbase/HBaseLocalTestUtils.java
- geaflow/geaflow-dsl/geaflow-dsl-connector/pom.xml
> [ISSUE-56] Support HBase Sink Connector

- geaflow-console/app/biz/shared/src/main/java/com/antgroup/geaflow/console/biz/shared/JobManager.java
- geaflow-console/app/biz/shared/src/main/java/com/antgroup/geaflow/console/biz/shared/convert/JobViewConverter.java
- geaflow-console/app/biz/shared/src/main/java/com/antgroup/geaflow/console/biz/shared/impl/JobManagerImpl.java
- geaflow-console/app/common/dal/src/main/java/com/antgroup/geaflow/console/common/dal/dao/ClusterDao.java
- geaflow-console/app/core/model/src/main/java/com/antgroup/geaflow/console/core/model/job/GeaflowApiJob.java
- geaflow-console/app/core/model/src/main/java/com/antgroup/geaflow/console/core/model/job/GeaflowCodeJob.java
- geaflow-console/app/core/model/src/main/java/com/antgroup/geaflow/console/core/model/job/GeaflowJob.java
- geaflow-console/app/core/model/src/main/java/com/antgroup/geaflow/console/core/model/release/GeaflowRelease.java
- geaflow-console/app/core/service/src/main/java/com/antgroup/geaflow/console/core/service/JobService.java
- geaflow-console/app/core/service/src/main/java/com/antgroup/geaflow/console/core/service/converter/JobConverter.java
- geaflow-console/app/core/service/src/main/java/com/antgroup/geaflow/console/core/service/release/GeaflowBuildPipeline.java
- geaflow-console/app/core/service/src/main/java/com/antgroup/geaflow/console/core/service/release/GenerateClusterConfigStage.java
- geaflow-console/app/core/service/src/main/java/com/antgroup/geaflow/console/core/service/release/GenerateJobConfigStage.java
- geaflow-console/app/core/service/src/main/java/com/antgroup/geaflow/console/core/service/release/GenerateJobPlanStage.java
- geaflow-console/app/core/service/src/main/java/com/antgroup/geaflow/console/core/service/release/PackageStage.java
- geaflow-console/app/core/service/src/main/java/com/antgroup/geaflow/console/core/service/release/ResolveReleaseVersionStage.java
- geaflow-console/app/core/service/src/main/java/com/antgroup/geaflow/console/core/service/runtime/ContainerRuntime.java
- geaflow-console/app/web/src/main/java/com/antgroup/geaflow/console/web/controller/api/JobController.java
1. Support create and submit HLA job in conosle.
> [ISSUE-107] Add api job backend module

- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/fetcher/PipelineInputFetcher.java
- geaflow/geaflow-core/geaflow-engine/geaflow-shuffle/src/main/java/com/antgroup/geaflow/shuffle/api/pipeline/fetcher/OneShardFetcher.java
Fix shuffle timer leakage, close the shuffle reader when after use.
> [ISSUE-110] Fix shuffle timer leakage

- build.sh
- docs/docs-cn/quick_start_docker.md
- docs/docs-en/quick_start_docker.md
- geaflow-console/app/biz/shared/src/main/java/com/antgroup/geaflow/console/biz/shared/impl/ReleaseManagerImpl.java
- geaflow-console/app/biz/shared/src/main/java/com/antgroup/geaflow/console/biz/shared/impl/TaskManagerImpl.java
- geaflow-console/app/common/util/src/main/java/com/antgroup/geaflow/console/common/util/type/GeaflowTaskStatus.java
- geaflow-console/app/core/model/src/main/java/com/antgroup/geaflow/console/core/model/runtime/GeaflowAudit.java
- geaflow-console/app/core/model/src/main/java/com/antgroup/geaflow/console/core/model/security/resource/TaskResource.java
- geaflow-console/app/core/service/src/main/java/com/antgroup/geaflow/console/core/service/TaskService.java
- geaflow-console/app/core/service/src/main/java/com/antgroup/geaflow/console/core/service/release/ResolveReleaseVersionStage.java
- geaflow-console/app/core/service/src/main/java/com/antgroup/geaflow/console/core/service/security/ResourceFactory.java
- geaflow-console/app/core/service/src/main/java/com/antgroup/geaflow/console/core/service/security/Resources.java
- geaflow-console/app/core/service/src/main/java/com/antgroup/geaflow/console/core/service/task/GeaflowTaskOperator.java
- geaflow-console/app/web/src/main/java/com/antgroup/geaflow/console/web/controller/api/TaskController.java
Issue: https://github.com/TuGraph-family/tugraph-analytics/issues/116
> [ISSUE-116] Support reset task and optimize operation logs

- geaflow-web/packages/app/client/package.json
- geaflow-web/packages/app/client/src/plugins/file-manager.ts
- geaflow-web/packages/app/server/package.json
- geaflow-web/packages/plugins/cluster-manage/package.json
- geaflow-web/packages/plugins/gea-flow-computing/package.json
- geaflow-web/packages/plugins/geaflow-function-manage/package.json
- geaflow-web/packages/plugins/geaflow-header/package.json
- geaflow-web/packages/plugins/geaflow-jarfile-manage/package.json
- geaflow-web/packages/plugins/geaflow-login/package.json
- geaflow-web/packages/plugins/geaflow-register/package.json
- geaflow-web/packages/plugins/graph-definition/package.json
- geaflow-web/packages/plugins/instance-list/package.json
- geaflow-web/packages/plugins/job-detail/package.json
- geaflow-web/packages/plugins/job-list/package.json
- geaflow-web/packages/plugins/quick-install/package.json
- geaflow-web/packages/plugins/table-definition/package.json
- geaflow-web/packages/plugins/tenant-manage/package.json
- geaflow-web/packages/plugins/user-manage/package.json
- geaflow-web/packages/plugins/version-manage/package.json
https://github.com/TuGraph-family/tugraph-analytics/issues/124
> [ISSUE-124] Fix yarn build error when build image for geaflow-web

- geaflow/geaflow-common/pom.xml
- geaflow/geaflow-dsl/geaflow-dsl-catalog/pom.xml
- geaflow/geaflow-dsl/geaflow-dsl-common/pom.xml
- geaflow/geaflow-dsl/geaflow-dsl-plan/pom.xml
- geaflow/geaflow-dsl/geaflow-dsl-runtime/pom.xml
- geaflow/geaflow-dsl/pom.xml
- geaflow/geaflow-state/geaflow-state-common/pom.xml
- geaflow/geaflow-state/geaflow-state-impl/pom.xml
1. Remove dependency duplicate imports
> [MINOR] Remove duplicate dependencies

- geaflow/geaflow-core/geaflow-runtime/geaflow-plan/src/main/java/com/antgroup/geaflow/plan/PipelinePlanBuilder.java
- geaflow/geaflow-core/geaflow-runtime/geaflow-plan/src/test/java/com/antgroup/geaflow/plan/PipelinePlanTest.java
A job will do checkpoint every 5 window by default. However a single window job should do checkpoint and finish after the only window done.
> [ISSUE-132] Do checkpoint after single window job finished

- geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/QueryClient.java
- geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/QueryContext.java
- geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/engine/GQLPipeLine.java
- geaflow/geaflow-dsl/geaflow-dsl-runtime/src/test/java/com/antgroup/geaflow/dsl/runtime/query/QueryTester.java
Optimize the step DAG for dsl test case to eliminate the duplicate graph build.
> [ISSUE-144] Optimize the step DAG for dsl test case

- geaflow-console/app/biz/shared/src/main/java/com/antgroup/geaflow/console/biz/shared/view/PluginConfigView.java
- geaflow-console/app/common/dal/src/main/java/com/antgroup/geaflow/console/common/dal/dao/IdDao.java
- geaflow-console/app/common/util/src/main/java/com/antgroup/geaflow/console/common/util/type/GeaflowFieldCategory.java
- geaflow-console/app/core/model/src/main/java/com/antgroup/geaflow/console/core/model/data/GeaflowEdge.java
- geaflow-console/app/core/model/src/main/java/com/antgroup/geaflow/console/core/model/data/GeaflowStruct.java
- geaflow-console/app/core/model/src/main/java/com/antgroup/geaflow/console/core/model/data/GeaflowVertex.java
- geaflow-console/app/core/service/src/main/java/com/antgroup/geaflow/console/core/service/file/OssFileClient.java
- geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/QueryClient.java
1. OSS URL format
2. pluginType null check
3. validate edge/vertex fields when create
> [ISSUE-149] Fix NPE for pluginType check

- geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-file/src/main/java/com/antgroup/geaflow/dsl/connector/file/sink/FileTableSink.java
- geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-file/src/main/java/com/antgroup/geaflow/dsl/connector/file/sink/FileWriteHandlers.java
- geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-file/src/main/java/com/antgroup/geaflow/dsl/connector/file/sink/LocalFileWriteHandler.java
- geaflow/geaflow-dsl/geaflow-dsl-runtime/src/test/java/com/antgroup/geaflow/dsl/runtime/query/KafkaFoTest.java
Currently we use the FileSystem to write data to local file.  The data may not flush for streaming writing.
Use he FileWriter can solve this issue.
> [ISSUE-170] Fix data not flush for local file writer

- geaflow/geaflow-common/src/main/java/com/antgroup/geaflow/common/config/keys/ConnectorConfigKeys.java
- geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-file/src/main/java/com/antgroup/geaflow/dsl/connector/file/source/AbstractFileReadHandler.java
- geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-file/src/main/java/com/antgroup/geaflow/dsl/connector/file/source/FileReadHandler.java
- geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-file/src/main/java/com/antgroup/geaflow/dsl/connector/file/source/FileTableSource.java
- geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-file/src/main/java/com/antgroup/geaflow/dsl/connector/file/source/format/CsvFormat.java
- geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-file/src/main/java/com/antgroup/geaflow/dsl/connector/file/source/format/FileFormat.java
- geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-file/src/main/java/com/antgroup/geaflow/dsl/connector/file/source/format/ParquetFormat.java
- geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-file/src/main/java/com/antgroup/geaflow/dsl/connector/file/source/format/TextFormat.java
- geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-file/src/main/resources/META-INF/services/com.antgroup.geaflow.dsl.connector.file.source.format.FileFormat
- geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-file/src/test/java/com/antgroup/geaflow/dsl/connector/file/CsvFormatTest.java
Support reading csv file format.
> [ISSUE-174] Support csv file format

- geaflow/geaflow-dsl/geaflow-dsl-common/src/main/java/com/antgroup/geaflow/dsl/common/util/TypeCastUtil.java
Fixed string type conversion accuracy loss
> [ISSUE-177] Fix type cast for string

- geaflow/geaflow-dsl/geaflow-dsl-catalog/src/main/java/com/antgroup/geaflow/dsl/schema/GeaFlowGraph.java
- geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/traversal/DagTopologyGroup.java
- geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/traversal/operator/StepLoopUntilOperator.java
- geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/traversal/operator/StepNodeFilterOperator.java
- geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/traversal/path/AbstractTreePath.java
Fix known bugs
Union construction issue
DAG iteration calculation error
TreePath Filter error
Graph field check error
> [ISSUE-181] Minor fix for dsl traversal

- geaflow/geaflow-common/src/main/java/com/antgroup/geaflow/common/binary/BinaryString.java
- geaflow/geaflow-common/src/test/java/com/antgroup/geaflow/common/binary/BinaryStringTest.java
- geaflow/geaflow-dsl/geaflow-dsl-plan/src/main/java/com/antgroup/geaflow/dsl/schema/function/GeaFlowBuiltinFunctions.java
- geaflow/geaflow-dsl/geaflow-dsl-plan/src/main/java/com/antgroup/geaflow/dsl/udf/table/string/ConcatWS.java
- geaflow/geaflow-dsl/geaflow-dsl-plan/src/main/java/com/antgroup/geaflow/dsl/udf/table/string/IsBlank.java
- geaflow/geaflow-dsl/geaflow-dsl-plan/src/main/java/com/antgroup/geaflow/dsl/udf/table/string/LTrim.java
- geaflow/geaflow-dsl/geaflow-dsl-plan/src/main/java/com/antgroup/geaflow/dsl/udf/table/string/RTrim.java
- geaflow/geaflow-dsl/geaflow-dsl-plan/src/test/java/com/antgroup/geaflow/dsl/udf/string/TrimTest.java
- geaflow/geaflow-dsl/geaflow-dsl-plan/src/test/java/com/antgroup/geaflow/dsl/udf/string/UDFStringTest.java
Support BinaryString as input type for trim function.
> [ISSUE-188] Support BinaryString as input for trim function

- geaflow/geaflow-dsl/geaflow-dsl-common/src/main/java/com/antgroup/geaflow/dsl/common/util/FunctionCallUtils.java
- geaflow/geaflow-dsl/geaflow-dsl-runtime/src/test/resources/query/project_002.sql
> [ISSUE-202] Fix NPE for null literal

- geaflow/geaflow-dsl/geaflow-dsl-common/src/main/java/com/antgroup/geaflow/dsl/common/util/FunctionCallUtils.java
- geaflow/geaflow-dsl/geaflow-dsl-common/src/main/java/com/antgroup/geaflow/dsl/common/util/TypeCastUtil.java
- geaflow/geaflow-dsl/geaflow-dsl-common/src/test/java/com/antgroup/geaflow/dsl/common/data/TypeCastUtilTest.java
- geaflow/geaflow-dsl/geaflow-dsl-plan/src/main/java/com/antgroup/geaflow/dsl/schema/function/GeaFlowBuiltinFunctions.java
- geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/expression/cast/CastExpression.java
Optimize type cast to reduce the if-else test.
> [ISSUE-205] Optimize type cast

- geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-file/src/main/java/com/antgroup/geaflow/dsl/connector/file/source/JarFileReadHandler.java
Throw exception when the resource path is not found.
> [ISSUE-204] Throw exception when resource path not found

- geaflow/geaflow-metrics/geaflow-metrics-influxdb/src/main/java/com/antgroup/geaflow/metrics/influxdb/InfluxdbReporter.java
- geaflow/geaflow-metrics/geaflow-metrics-reporter/src/main/java/com/antgroup/geaflow/metrics/reporter/AbstractReporter.java
remove useless metric tag `namespace`
> [ISSUE-220] remove metric tag namespace

- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/clustermanager/AbstractClusterManager.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/heartbeat/HeartbeatSender.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/rpc/IContainerEndpointRef.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/rpc/IMasterEndpointRef.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/rpc/RpcClient.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/rpc/RpcEndpointRefFactory.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/rpc/impl/AbstractRpcEndpointRef.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/rpc/impl/ContainerEndpointRef.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/rpc/impl/DriverEndpointRef.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/rpc/impl/MasterEndpointRef.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/rpc/impl/MetricEndpointRef.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/rpc/impl/PipelineMasterEndpointRef.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/rpc/impl/ResourceManagerEndpointRef.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/web/metrics/MetricFetcher.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/test/java/com/antgroup/geaflow/cluster/rpc/AsyncRpcTest.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/test/java/com/antgroup/geaflow/cluster/rpc/RpcEndpointRefTest.java
Invalidate resource data cache if async rpc failed
> [ISSUE-223] invalid resource data if async rpc failed.

- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/clustermanager/ClusterContext.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/common/AbstractComponent.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/common/ReliableContainerContext.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/constants/ClusterConstants.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/container/ContainerContext.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/driver/DriverContext.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/master/MasterContext.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/resourcemanager/DefaultResourceManager.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/system/ClusterMetaStore.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/system/RocksdbClusterMetaKVStore.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/test/java/com/antgroup/geaflow/cluster/container/ContainerContextTest.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/test/java/com/antgroup/geaflow/cluster/driver/DriverContextTest.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/test/java/com/antgroup/geaflow/cluster/resourcemanager/DefaultResourceManagerTest.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/test/java/com/antgroup/geaflow/cluster/rpc/AsyncRpcTest.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/test/java/com/antgroup/geaflow/cluster/system/ClusterMetaStoreTest.java
- geaflow/geaflow-core/geaflow-runtime/geaflow-runtime-core/src/test/java/com/antgroup/geaflow/runtime/core/scheduler/ExecutionGraphCycleSchedulerTest.java
- geaflow/geaflow-core/geaflow-runtime/geaflow-runtime-core/src/test/java/com/antgroup/geaflow/runtime/core/scheduler/PipelineCycleSchedulerTest.java
- geaflow/geaflow-core/geaflow-runtime/geaflow-runtime-core/src/test/java/com/antgroup/geaflow/runtime/core/scheduler/context/AbstractCycleSchedulerContextTest.java
- geaflow/geaflow-core/geaflow-runtime/geaflow-runtime-core/src/test/java/com/antgroup/geaflow/runtime/core/scheduler/context/CheckpointSchedulerContextTest.java
- geaflow/geaflow-core/geaflow-runtime/geaflow-runtime-core/src/test/java/com/antgroup/geaflow/runtime/core/scheduler/context/IterationRedoSchedulerContextTest.java
- geaflow/geaflow-core/geaflow-runtime/geaflow-runtime-core/src/test/java/com/antgroup/geaflow/runtime/core/scheduler/resource/BaseScheduledWorkerManagerTest.java
fix ClusterMetaStore save conflicts on driver multi-thread case
> [ISSUE-225] fix cluster meta save conflict.

- build.sh
- docs/docs-cn/quick_start_operator.md
- docs/docs-en/quick_start_operator.md
- geaflow-kubernetes-operator/build-operator.sh
- geaflow-kubernetes-operator/example/example.yml
- geaflow-kubernetes-operator/example/example_dsl.yml
- geaflow-kubernetes-operator/example/example_hla.yml
- geaflow-kubernetes-operator/geaflow-kubernetes-operator-core/src/main/java/com/antgroup/geaflow/kubernetes/operator/core/reconciler/GeaflowJobReconciler.java
- geaflow/geaflow-deploy/docker/Dockerfile
- geaflow/geaflow-deploy/docker/start-agent.sh
- geaflow/geaflow-deploy/geaflow-on-k8s/pom.xml
- geaflow/geaflow-deploy/geaflow-on-k8s/src/main/java/com/antgroup/geaflow/cluster/k8s/clustermanager/KubernetesResourceBuilder.java
- geaflow/geaflow-deploy/geaflow-on-k8s/src/main/java/com/antgroup/geaflow/cluster/k8s/config/AbstractKubernetesParam.java
- geaflow/geaflow-deploy/geaflow-on-k8s/src/main/java/com/antgroup/geaflow/cluster/k8s/config/K8SConstants.java
- geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-hive/pom.xml
- geaflow/pom.xml
1. Optimize the shell script and dockerfile to build image.
2. Fix a bug of geaflow-kubernetes-operator which can lead to submitting job fail.
3. Fix a bug of geaflow-on-k8s which makes log4j properties invalid.
4. Optimize the docs for quick-start of geaflow-kubernetes-operator.
> [ISSUE-245] Fix some proplems of geaflow-kubernetes-operator and geaflow-on-k8s

- geaflow/geaflow-deploy/docker/Dockerfile-arm64
> [ISSUE-247] Fix dockerfile-arm64

- geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-file/pom.xml
- geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-file/src/main/java/com/antgroup/geaflow/dsl/connector/file/FileConnectorUtil.java
- geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-file/src/main/java/com/antgroup/geaflow/dsl/connector/file/FileConstants.java
- geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-file/src/main/java/com/antgroup/geaflow/dsl/connector/file/sink/FileWriteHandlers.java
- geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-file/src/main/java/com/antgroup/geaflow/dsl/connector/file/sink/LocalFileWriteHandler.java
- geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-file/src/main/java/com/antgroup/geaflow/dsl/connector/file/sink/S3FileWriteHandler.java
- geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-file/src/main/java/com/antgroup/geaflow/dsl/connector/file/source/FileReadHandlers.java
- geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-file/src/main/java/com/antgroup/geaflow/dsl/connector/file/source/S3FileReadHandler.java
> [ISSUE-244] Support s3 for file connector

- README.md
- README_cn.md
- geaflow-console/Dockerfile
Issue: https://github.com/TuGraph-family/tugraph-analytics/issues/252
> Fix docker build copy error of console

- geaflow/geaflow-core/geaflow-runtime/geaflow-operator/src/main/java/com/antgroup/geaflow/operator/impl/graph/algo/vc/GraphVertexCentricOpFactory.java
- geaflow/geaflow-core/geaflow-runtime/geaflow-plan/src/main/java/com/antgroup/geaflow/core/graph/builder/ExecutionGraphBuilder.java
- geaflow/geaflow-core/geaflow-runtime/geaflow-plan/src/test/java/com/antgroup/geaflow/core/graph/builder/ExecutionGraphBuilderTest.java
Fix execution group build error when occur multi graph traversal
> [ISSUE-256] Fix execution group build error for multi graph traversal 

- geaflow/geaflow-common/src/main/java/com/antgroup/geaflow/common/config/keys/ExecutionConfigKeys.java
- geaflow/geaflow-deploy/geaflow-assembly/pom.xml
- geaflow/geaflow-metrics/geaflow-metrics-prometheus/pom.xml
- geaflow/geaflow-metrics/geaflow-metrics-prometheus/src/main/java/com/antgroup/geaflow/metrics/prometheus/PrometheusConfigKeys.java
- geaflow/geaflow-metrics/geaflow-metrics-prometheus/src/main/java/com/antgroup/geaflow/metrics/prometheus/PrometheusReporter.java
- geaflow/geaflow-metrics/geaflow-metrics-prometheus/src/main/resources/META-INF/services/com.antgroup.geaflow.metrics.common.reporter.MetricReporter
- geaflow/geaflow-metrics/geaflow-metrics-prometheus/src/test/java/com/antgroup/geaflow/metrics/prometheus/PrometheusReporterTest.java
- geaflow/pom.xml
Support to report metrics to Prometheus.
> [ISSUE-269] Support to report metrics to Prometheus

- geaflow/geaflow-plugins/geaflow-store/pom.xml
- geaflow/geaflow-state/geaflow-state-impl/pom.xml
- geaflow/geaflow-state/geaflow-state-impl/src/test/java/com/antgroup/geaflow/state/CStoreGraphStateTest.java
- geaflow/geaflow-state/geaflow-state-impl/src/test/java/com/antgroup/geaflow/state/StaticGraphStateTest.java
- geaflow/geaflow-state/geaflow-state-strategy/pom.xml
- geaflow/pom.xml
Fix the error in packaging of cstore cannot find
> [ISSUE-272] Fix compile failed for load cstore dependency

- geaflow/geaflow-dsl/geaflow-dsl-common/src/main/java/com/antgroup/geaflow/dsl/common/algo/AlgorithmUserFunction.java
- geaflow/geaflow-dsl/geaflow-dsl-plan/src/main/java/com/antgroup/geaflow/dsl/rel/GraphAlgorithm.java
- geaflow/geaflow-dsl/geaflow-dsl-plan/src/main/java/com/antgroup/geaflow/dsl/schema/function/GeaFlowUserDefinedGraphAlgorithm.java
- geaflow/geaflow-dsl/geaflow-dsl-plan/src/main/java/com/antgroup/geaflow/dsl/udf/graph/KHop.java
- geaflow/geaflow-dsl/geaflow-dsl-plan/src/main/java/com/antgroup/geaflow/dsl/udf/graph/PageRank.java
- geaflow/geaflow-dsl/geaflow-dsl-plan/src/main/java/com/antgroup/geaflow/dsl/udf/graph/SingleSourceShortestPath.java
- geaflow/geaflow-dsl/geaflow-dsl-plan/src/main/java/com/antgroup/geaflow/dsl/udf/ldbc/BICityInteractionAlgorithm.java
- geaflow/geaflow-dsl/geaflow-dsl-plan/src/main/java/com/antgroup/geaflow/dsl/udf/ldbc/BIConnectionPathAlgorithm.java
- geaflow/geaflow-dsl/geaflow-dsl-plan/src/main/java/com/antgroup/geaflow/dsl/udf/ldbc/BIRecruitmentAlgorithm.java
- geaflow/geaflow-dsl/geaflow-dsl-plan/src/test/java/com/antgroup/geaflow/dsl/GQLToRelConverterTest.java
- geaflow/geaflow-dsl/geaflow-dsl-plan/src/test/java/com/antgroup/geaflow/dsl/GQLValidateGraphAlgorithmTest.java
Support for UDGA definition-aware GraphSchema
> [ISSUE-274] Support schema aware for UDGA function

- geaflow/geaflow-common/src/main/java/com/antgroup/geaflow/common/config/keys/ExecutionConfigKeys.java
- geaflow/geaflow-common/src/main/java/com/antgroup/geaflow/common/rpc/ConfigurableClientOption.java
- geaflow/geaflow-common/src/main/java/com/antgroup/geaflow/common/rpc/ConfigurableServerOption.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/clustermanager/AbstractClusterManager.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/clustermanager/Supervisor.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/common/AbstractComponent.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/common/AbstractContainer.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/heartbeat/HeartbeatManager.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/rpc/ISupervisorEndpoint.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/rpc/ISupervisorEndpointRef.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/rpc/RpcClient.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/rpc/impl/MetricEndpointRef.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/rpc/impl/SupervisorEndpoint.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/rpc/impl/SupervisorEndpointRef.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/web/metrics/MetricFetcher.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/web/metrics/MetricServer.java
- geaflow/geaflow-core/geaflow-engine/geaflow-rpc-proto/src/main/java/com/antgroup/geaflow/rpc/proto/Supervisor.java
- geaflow/geaflow-core/geaflow-engine/geaflow-rpc-proto/src/main/java/com/antgroup/geaflow/rpc/proto/SupervisorServiceGrpc.java
- geaflow/geaflow-core/geaflow-engine/geaflow-rpc-proto/src/main/proto/supervisor.proto
- geaflow/geaflow-deploy/geaflow-on-k8s/src/main/java/com/antgroup/geaflow/cluster/k8s/clustermanager/KubernetesClusterManager.java
- geaflow/geaflow-deploy/geaflow-on-k8s/src/main/java/com/antgroup/geaflow/cluster/k8s/entrypoint/KubernetesSupervisorRunner.java
Optimize the heartbeat loss detection time.  
Resolve #279
> [ISSUE-279] optimize the heartbeat detection

- geaflow-cstore/java/pom.xml
- geaflow/geaflow-plugins/geaflow-store/pom.xml
- geaflow/geaflow-state/geaflow-state-impl/pom.xml
- geaflow/geaflow-state/geaflow-state-impl/src/test/java/com/antgroup/geaflow/state/CStoreGraphStateTest.java
- geaflow/geaflow-state/geaflow-state-impl/src/test/java/com/antgroup/geaflow/state/StaticGraphStateTest.java
- geaflow/geaflow-state/geaflow-state-strategy/pom.xml
- geaflow/pom.xml
https://github.com/TuGraph-family/tugraph-analytics/issues/281
Rejoin the CStore module
> [ISSUE-281] Add cstore module

- geaflow/geaflow-core/geaflow-api/src/main/java/com/antgroup/geaflow/api/graph/function/vc/IncVertexCentricTraversalFunction.java
- geaflow/geaflow-core/geaflow-api/src/main/java/com/antgroup/geaflow/api/graph/function/vc/VertexCentricTraversalFunction.java
- geaflow/geaflow-core/geaflow-runtime/geaflow-operator/src/main/java/com/antgroup/geaflow/operator/impl/graph/traversal/dynamic/AbstractDynamicGraphVertexCentricTraversalOp.java
- geaflow/geaflow-core/geaflow-runtime/geaflow-operator/src/main/java/com/antgroup/geaflow/operator/impl/graph/traversal/statical/AbstractStaticGraphVertexCentricTraversalOp.java
- geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/engine/GeaFlowAlgorithmAggTraversalFunction.java
- geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/engine/GeaFlowAlgorithmDynamicAggTraversalFunction.java
- geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/util/QueryUtil.java
Fix the exception of Incremental Graph Algorithm downloading state from remote
> [ISSUE-284] Fix loading state error for user defined graph algorithm

- geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/engine/GQLPipeLine.java
- geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/engine/GeaFlowAlgorithmAggTraversalFunction.java
- geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/engine/GeaFlowAlgorithmDynamicAggTraversalFunction.java
Fix the redundant persistence of meta information in the memory graph
> [ISSUE-288] Fix redundant persistence of meta information in the memory graph

- geaflow/geaflow-core/geaflow-runtime/geaflow-operator/src/main/java/com/antgroup/geaflow/context/AbstractRuntimeContext.java
- geaflow/geaflow-core/geaflow-runtime/geaflow-runtime-core/src/main/java/com/antgroup/geaflow/runtime/core/context/DefaultRuntimeContext.java
Fix WindowId not update in runtime context
> [ISSUE-290] Fix WindowId not update in runtime context

- geaflow/geaflow-common/src/main/java/com/antgroup/geaflow/common/config/keys/ExecutionConfigKeys.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/master/AbstractMaster.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/rpc/RpcClient.java
- geaflow/geaflow-core/geaflow-engine/geaflow-highavailability/src/main/java/com/antgroup/geaflow/ha/leaderelection/ILeaderContender.java
- geaflow/geaflow-core/geaflow-engine/geaflow-highavailability/src/main/java/com/antgroup/geaflow/ha/leaderelection/ILeaderElectionDriver.java
- geaflow/geaflow-core/geaflow-engine/geaflow-highavailability/src/main/java/com/antgroup/geaflow/ha/leaderelection/ILeaderElectionEventListener.java
- geaflow/geaflow-core/geaflow-engine/geaflow-highavailability/src/main/java/com/antgroup/geaflow/ha/leaderelection/ILeaderElectionService.java
- geaflow/geaflow-core/geaflow-engine/geaflow-highavailability/src/main/java/com/antgroup/geaflow/ha/leaderelection/LeaderContenderType.java
- geaflow/geaflow-core/geaflow-engine/geaflow-highavailability/src/main/java/com/antgroup/geaflow/ha/leaderelection/LeaderElectionServiceFactory.java
- geaflow/geaflow-core/geaflow-engine/geaflow-highavailability/src/main/java/com/antgroup/geaflow/ha/leaderelection/LeaderElectionServiceType.java
- geaflow/geaflow-deploy/geaflow-on-k8s/src/main/java/com/antgroup/geaflow/cluster/k8s/client/KubernetesJobClient.java
- geaflow/geaflow-deploy/geaflow-on-k8s/src/main/java/com/antgroup/geaflow/cluster/k8s/clustermanager/GeaflowKubeClient.java
- geaflow/geaflow-deploy/geaflow-on-k8s/src/main/java/com/antgroup/geaflow/cluster/k8s/clustermanager/KubernetesClusterManager.java
- geaflow/geaflow-deploy/geaflow-on-k8s/src/main/java/com/antgroup/geaflow/cluster/k8s/clustermanager/KubernetesResourceBuilder.java
- geaflow/geaflow-deploy/geaflow-on-k8s/src/main/java/com/antgroup/geaflow/cluster/k8s/config/AbstractKubernetesParam.java
- geaflow/geaflow-deploy/geaflow-on-k8s/src/main/java/com/antgroup/geaflow/cluster/k8s/config/K8SConstants.java
- geaflow/geaflow-deploy/geaflow-on-k8s/src/main/java/com/antgroup/geaflow/cluster/k8s/config/KubernetesConfigKeys.java
- geaflow/geaflow-deploy/geaflow-on-k8s/src/main/java/com/antgroup/geaflow/cluster/k8s/config/KubernetesMasterParam.java
- geaflow/geaflow-deploy/geaflow-on-k8s/src/main/java/com/antgroup/geaflow/cluster/k8s/config/KubernetesParam.java
- geaflow/geaflow-deploy/geaflow-on-k8s/src/main/java/com/antgroup/geaflow/cluster/k8s/entrypoint/KubernetesMasterRunner.java
- geaflow/geaflow-deploy/geaflow-on-k8s/src/main/java/com/antgroup/geaflow/cluster/k8s/leaderelection/KubernetesLeaderElectionService.java
- geaflow/geaflow-deploy/geaflow-on-k8s/src/main/java/com/antgroup/geaflow/cluster/k8s/leaderelection/KubernetesLeaderElector.java
- geaflow/geaflow-deploy/geaflow-on-k8s/src/main/java/com/antgroup/geaflow/cluster/k8s/leaderelection/KubernetesLeaderElectorConfig.java
- geaflow/geaflow-deploy/geaflow-on-k8s/src/main/resources/META-INF/services/com.antgroup.geaflow.ha.leaderelection.ILeaderElectionService
- geaflow/geaflow-deploy/geaflow-on-k8s/src/test/java/com/antgroup/geaflow/cluster/k8s/clustermanager/KubernetesClusterManagerTest.java
Add leader-election for master to ensure highavailability
> [ISSUE-296] Add leader-election for master to ensure highavailability

- geaflow/geaflow-core/geaflow-runtime/geaflow-operator/src/main/java/com/antgroup/geaflow/operator/impl/graph/traversal/dynamic/AbstractDynamicGraphVertexCentricTraversalOp.java
- geaflow/geaflow-core/geaflow-runtime/geaflow-operator/src/main/java/com/antgroup/geaflow/operator/impl/graph/traversal/statical/AbstractStaticGraphVertexCentricTraversalOp.java
- geaflow/geaflow-core/geaflow-runtime/geaflow-runtime-core/src/main/java/com/antgroup/geaflow/runtime/core/scheduler/context/AbstractCycleSchedulerContext.java
- geaflow/geaflow-core/geaflow-runtime/geaflow-runtime-core/src/main/java/com/antgroup/geaflow/runtime/core/worker/impl/ComputeWorker.java
https://github.com/TuGraph-family/tugraph-analytics/issues/306
Add some debug logs for Traversal Operator
> [ISSUE-306] Add some logs for Traversal Operator

- geaflow/geaflow-common/src/main/java/com/antgroup/geaflow/common/config/keys/StateConfigKeys.java
- geaflow/geaflow-core/geaflow-runtime/geaflow-operator/src/main/java/com/antgroup/geaflow/operator/impl/graph/traversal/dynamic/AbstractDynamicGraphVertexCentricTraversalOp.java
- geaflow/geaflow-core/geaflow-runtime/geaflow-runtime-core/src/main/java/com/antgroup/geaflow/runtime/core/scheduler/context/AbstractCycleSchedulerContext.java
- geaflow/geaflow-plugins/geaflow-store/geaflow-store-rocksdb/src/main/java/com/antgroup/geaflow/store/rocksdb/RocksdbPersistClient.java
Add Timeout config for RocksDB when connecting to OSS to prevent falling into an infinite wait
> [ISSUE-308] Add Timeout config for RocksDB when connecting to OSS

- geaflow/pom.xml
> [ISSUE-297] Upgrade log4j-core version to 2.17.1

- docs/docs-cn/quick_start_operator.md
- docs/docs-en/quick_start_operator.md
- geaflow-kubernetes-operator/example/example.yml
- geaflow-kubernetes-operator/example/example_hla.yml
> [docs] Use KHop instead of SSSP as the example of geaflow-kubernetes-operator

- geaflow/geaflow-deploy/geaflow-cluster-runner/src/main/java/com/antgroup/geaflow/cluster/runner/manager/GeaFlowClusterManager.java
- geaflow/geaflow-deploy/geaflow-on-k8s/src/main/java/com/antgroup/geaflow/cluster/k8s/config/KubernetesDriverParam.java
- geaflow/geaflow-deploy/geaflow-on-k8s/src/main/java/com/antgroup/geaflow/cluster/k8s/config/KubernetesMasterParam.java
fix container jvm parameters
Resolve #312
> [ISSUE-312] fix container start command parameters

- geaflow/geaflow-core/geaflow-runtime/geaflow-pipeline/src/main/java/com/antgroup/geaflow/runtime/pipeline/runner/PipelineRunner.java
- geaflow/geaflow-core/geaflow-runtime/geaflow-runtime-core/src/main/java/com/antgroup/geaflow/runtime/core/scheduler/AbstractCycleScheduler.java
- geaflow/geaflow-core/geaflow-runtime/geaflow-runtime-core/src/main/java/com/antgroup/geaflow/runtime/core/scheduler/ExecutionGraphCycleScheduler.java
- geaflow/geaflow-core/geaflow-runtime/geaflow-runtime-core/src/main/java/com/antgroup/geaflow/runtime/core/scheduler/PipelineCycleScheduler.java
- geaflow/geaflow-core/geaflow-runtime/geaflow-runtime-core/src/main/java/com/antgroup/geaflow/runtime/core/scheduler/SchedulerEventDispatcher.java
- geaflow/geaflow-core/geaflow-runtime/geaflow-runtime-core/src/main/java/com/antgroup/geaflow/runtime/core/scheduler/response/AbstractFixedSizeEventHandler.java
- geaflow/geaflow-core/geaflow-runtime/geaflow-runtime-core/src/main/java/com/antgroup/geaflow/runtime/core/scheduler/response/ComputeFinishEventListener.java
- geaflow/geaflow-core/geaflow-runtime/geaflow-runtime-core/src/main/java/com/antgroup/geaflow/runtime/core/scheduler/response/EventListenerKey.java
- geaflow/geaflow-core/geaflow-runtime/geaflow-runtime-core/src/main/java/com/antgroup/geaflow/runtime/core/scheduler/response/SourceFinishResponseEventListener.java
- geaflow/geaflow-core/geaflow-runtime/geaflow-runtime-core/src/main/java/com/antgroup/geaflow/runtime/core/scheduler/strategy/TopologicalOrderScheduleStrategy.java
register event listener when submit event to worker
then received response will dispatch to event listener to handle.
> [ISSUE-314] add event listener for scheduler.

- geaflow-cstore/Cargo.lock
- geaflow-cstore/Cargo.toml
- geaflow-cstore/src/file/file_operator/opendal_file_operator.rs
- geaflow-cstore/src/util/test_util.rs
> [ISSUE-323] upgrade opendal version to 0.43.0

- geaflow/geaflow-deploy/geaflow-on-k8s/src/main/java/com/antgroup/geaflow/cluster/k8s/client/KubernetesClusterClient.java
- geaflow/geaflow-deploy/geaflow-on-k8s/src/main/java/com/antgroup/geaflow/cluster/k8s/config/K8SConstants.java
#332  add a prefix 'geaflow' to random cluster id
> [ISSUE-332] add a prefix to random cluster id

- CODE_OF_CONDUCT.md
- community/CONTRIBUTING.md
- community/ROLES.md
- Adopting the Contributor Covenant Code of Conduct
- Add Contributing Guidelines
- Describe Roles and Responsibilities referencing the Apache Way
-N/A
> [DOC]: Add community governance guidelines

- geaflow/geaflow-examples/pom.xml
- geaflow/geaflow-model/src/main/java/com/antgroup/geaflow/model/graph/edge/IEdge.java
- geaflow/geaflow-model/src/main/java/com/antgroup/geaflow/model/graph/vertex/IVertex.java
[ISSUE-385] Fix compile warning
> [ISSUE-385] Fix compile java doc warning

- geaflow/geaflow-core/geaflow-runtime/geaflow-operator/src/main/java/com/antgroup/geaflow/operator/impl/graph/algo/vc/AbstractGraphVertexCentricOp.java
- geaflow/geaflow-core/geaflow-runtime/geaflow-runtime-core/src/main/java/com/antgroup/geaflow/runtime/core/scheduler/resource/AbstractScheduledWorkerManager.java
- geaflow/geaflow-core/geaflow-runtime/geaflow-runtime-core/src/main/java/com/antgroup/geaflow/runtime/core/scheduler/resource/CheckpointCycleScheduledWorkerManager.java
- geaflow/geaflow-core/geaflow-runtime/geaflow-runtime-core/src/main/java/com/antgroup/geaflow/runtime/core/scheduler/resource/TaskAssigner.java
- geaflow/geaflow-core/geaflow-runtime/geaflow-runtime-core/src/test/java/com/antgroup/geaflow/runtime/core/scheduler/resource/CheckpointScheduledWorkerManagerTest.java
> [ISSUE-392] Affinity Scheduling Optimization

- geaflow/geaflow-dsl/geaflow-dsl-plan/src/main/java/com/antgroup/geaflow/dsl/schema/function/BuildInSqlFunctionTable.java
- geaflow/geaflow-dsl/geaflow-dsl-plan/src/main/java/com/antgroup/geaflow/dsl/udf/graph/AllSourceShortestPath.java
- geaflow/geaflow-dsl/geaflow-dsl-runtime/src/test/java/com/antgroup/geaflow/dsl/runtime/query/GQLAlgorithmTest.java
- geaflow/geaflow-dsl/geaflow-dsl-runtime/src/test/resources/expect/gql_algorithm_inc_assp.txt
- geaflow/geaflow-dsl/geaflow-dsl-runtime/src/test/resources/query/gql_algorithm_inc_assp.sql
> [ISSUE-389] Incremental All-Pairs Shortest Paths

- geaflow-console/app/common/service/integration/src/main/java/com/antgroup/geaflow/console/common/service/integration/engine/IPersistentIO.java
- geaflow/geaflow-infer/src/main/java/com/antgroup/geaflow/infer/util/InferFileUtils.java
- geaflow/geaflow-plugins/geaflow-file/geaflow-file-common/src/main/java/com/antgroup/geaflow/file/IPersistentIO.java
- geaflow/geaflow-plugins/geaflow-file/geaflow-file-dfs/src/main/java/com/antgroup/geaflow/file/dfs/DfsIO.java
- geaflow/geaflow-plugins/geaflow-file/geaflow-file-dfs/src/test/java/com/antgroup/geaflow/file/dfs/DfsIOTest.java
- geaflow/geaflow-plugins/geaflow-file/geaflow-file-dfs/src/test/java/com/antgroup/geaflow/file/dfs/LocalIOTest.java
- geaflow/geaflow-plugins/geaflow-file/geaflow-file-oss/src/main/java/com/antgroup/geaflow/file/oss/OssIO.java
- geaflow/geaflow-plugins/geaflow-file/geaflow-file-oss/src/test/java/com/antgroup/geaflow/file/oss/OssIOTest.java
- geaflow/geaflow-plugins/geaflow-store/geaflow-store-rocksdb/src/main/java/com/antgroup/geaflow/store/rocksdb/RocksdbPersistClient.java
- geaflow/geaflow-plugins/geaflow-view-meta/src/main/java/com/antgroup/geaflow/view/meta/ViewMeta.java
Standardize the persistent IO interface to support OSS/DFS/S3.
- [✅] Tests have Added for the changes
> [ISSUE-399] Standardized interfaces for OSS/DFS/S3

- geaflow/geaflow-dashboard/web-dashboard/src/pages/Component/Runtime/Logs.tsx
- geaflow/geaflow-dashboard/web-dashboard/src/pages/Component/Runtime/Metrics.tsx
- geaflow/geaflow-dashboard/web-dashboard/src/requestErrorConfig.ts
- geaflow/geaflow-dashboard/web-dashboard/src/services/jobs/api.ts
- geaflow/geaflow-deploy/docker/udf-downloader.py
fix the error display in dashboard font-end and the log date in deploy.log
resolve https://github.com/TuGraph-family/tugraph-analytics/issues/440
> [ISSUE-440] fix the error display in dashboard font-end and the date format in deploy.log

- geaflow/geaflow-common/src/main/java/com/antgroup/geaflow/common/exception/GeaflowHeartbeatException.java
- geaflow/geaflow-common/src/main/java/com/antgroup/geaflow/common/utils/ProcessUtil.java
- geaflow/geaflow-common/src/test/java/com/antgroup/geaflow/common/utils/ProcessUtilTest.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/clustermanager/ClusterContext.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/fetcher/PipelineInputFetcher.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/heartbeat/HeartbeatManager.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/runner/CommandRunner.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/runner/Supervisor.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/system/ClusterMetaStore.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/test/java/com/antgroup/geaflow/cluster/heartbeat/HeartbeatManagerTest.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/test/java/com/antgroup/geaflow/cluster/runner/SupervisorTest.java
- geaflow/geaflow-core/geaflow-engine/geaflow-shuffle/src/main/java/com/antgroup/geaflow/shuffle/pipeline/slice/SpillablePipelineSlice.java
- geaflow/geaflow-core/geaflow-runtime/geaflow-operator/src/test/java/com/antgroup/geaflow/operator/impl/graph/compute/dynamic/DynamicGraphVertexCentricComputeOpTest.java
- geaflow/geaflow-deploy/geaflow-cluster-runner/src/main/java/com/antgroup/geaflow/cluster/runner/entrypoint/ContainerRunner.java
- geaflow/geaflow-deploy/geaflow-cluster-runner/src/main/java/com/antgroup/geaflow/cluster/runner/entrypoint/DriverRunner.java
- geaflow/geaflow-deploy/geaflow-cluster-runner/src/main/java/com/antgroup/geaflow/cluster/runner/failover/ClusterFailoverStrategy.java
- geaflow/geaflow-deploy/geaflow-cluster-runner/src/main/java/com/antgroup/geaflow/cluster/runner/failover/ComponentFailoverStrategy.java
- geaflow/geaflow-deploy/geaflow-on-k8s/src/main/java/com/antgroup/geaflow/cluster/k8s/entrypoint/KubernetesClientRunner.java
- [ Y] Tests have Added for the changes
- [ Y] Production environment verified
> [ISSUE-447] fix cluster fo failure

- README.md
- README_cn.md
- docs/docs-cn/source/1.guide.md
- docs/docs-cn/source/3.quick_start/1.quick_start.md
- docs/docs-cn/source/3.quick_start/2.quick_start_docker.md
- docs/docs-en/source/1.guide.md
- docs/docs-en/source/3.quick_start/1.quick_start.md
- docs/docs-en/source/3.quick_start/2.quick_start_docker.md
> [ISSUE-451]fix document errors

- geaflow/geaflow-common/src/main/java/com/antgroup/geaflow/common/config/keys/ExecutionConfigKeys.java
- geaflow/geaflow-common/src/main/java/com/antgroup/geaflow/common/utils/ProcessUtil.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/heartbeat/HeartbeatManager.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/heartbeat/HeartbeatSender.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/rpc/RpcClient.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/runner/CommandRunner.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/runner/Supervisor.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/test/java/com/antgroup/geaflow/cluster/heartbeat/HeartbeatManagerTest.java
- geaflow/geaflow-deploy/geaflow-cluster-runner/pom.xml
- geaflow/geaflow-deploy/geaflow-cluster-runner/src/main/java/com/antgroup/geaflow/cluster/runner/entrypoint/ContainerRunner.java
- geaflow/geaflow-deploy/geaflow-cluster-runner/src/main/java/com/antgroup/geaflow/cluster/runner/entrypoint/DriverRunner.java
- geaflow/geaflow-deploy/geaflow-cluster-runner/src/main/java/com/antgroup/geaflow/cluster/runner/failover/ClusterFailoverStrategy.java
- geaflow/geaflow-deploy/geaflow-cluster-runner/src/main/java/com/antgroup/geaflow/cluster/runner/manager/GeaFlowClusterManager.java
- geaflow/geaflow-deploy/geaflow-cluster-runner/src/main/java/com/antgroup/geaflow/cluster/runner/util/ClusterUtils.java
- geaflow/geaflow-deploy/geaflow-cluster-runner/src/test/java/com/antgroup/geaflow/cluster/runner/util/ClusterUtilsTest.java
- geaflow/geaflow-deploy/geaflow-on-k8s/src/main/java/com/antgroup/geaflow/cluster/k8s/clustermanager/KubernetesClusterManager.java
- geaflow/geaflow-deploy/geaflow-on-k8s/src/main/java/com/antgroup/geaflow/cluster/k8s/config/KubernetesContainerParam.java
- geaflow/geaflow-deploy/geaflow-on-k8s/src/main/java/com/antgroup/geaflow/cluster/k8s/config/KubernetesDriverParam.java
- geaflow/geaflow-deploy/geaflow-on-ray/src/main/java/com/antgroup/geaflow/cluster/ray/clustermanager/RayClusterManager.java
- [Y ] Tests have Added for the changes
- [Y] Production environment verified
resolve #456
> [ISSUE-456] Optimize process exit logic

- docs/docs-cn/source/3.quick_start/1.quick_start.md
> rename brand name to geaflow

- geaflow/geaflow-common/src/main/java/com/antgroup/geaflow/common/config/keys/DSLConfigKeys.java
- geaflow/geaflow-dsl/geaflow-dsl-runtime/src/main/java/com/antgroup/geaflow/dsl/runtime/engine/GQLPipeLine.java
- geaflow/geaflow-examples/gql/sql_join_to_graph_demo.sql
- geaflow/geaflow-examples/src/test/java/com/antgroup/geaflow/example/base/BaseQueryTest.java
- geaflow/geaflow-examples/src/test/java/com/antgroup/geaflow/example/dsl/DemoCaseTest.java
- geaflow/geaflow-examples/src/test/resources/expect/sql_join_to_graph_demo.txt
Add local join sql to graph demo case
> Add local join sql to graph demo case

- README.md
- docs/docs-cn/source/3.quick_start/1.quick_start.md
- docs/docs-cn/source/3.quick_start/4.quick_start_sql_to_graph.md
- docs/docs-en/source/3.quick_start/1.quick_start.md
- docs/docs-en/source/3.quick_start/4.quick_start_sql_to_graph.md
[Doc] Add sql join quick start document
> [Doc] Add sql join quick start document

- bin/gql_submit.sh
The submission of two gql files simultaneously using `gql_submit` failed due to a port conflict related to the dashboard.
> The submission of two gql files simultaneously using `gql_submit` failed due to a port conflict related to the dashboard. 

- geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-jdbc/src/main/java/com/antgroup/geaflow/dsl/connector/jdbc/JDBCTableSource.java
- geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-jdbc/src/main/java/com/antgroup/geaflow/dsl/connector/jdbc/util/JDBCUtils.java
- geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-jdbc/src/test/java/com/antgroup/geaflow/dsl/connector/jdbc/JDBCTableConnectorTest.java
- geaflow/geaflow-dsl/geaflow-dsl-runtime/src/test/java/com/antgroup/geaflow/dsl/runtime/query/JDBCTest.java
Resolved SQL compatibility issues when pulling data via JDBC.
> [ISSUE-501] Fix JDBC fetch data sql compatible

- geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-jdbc/src/main/java/com/antgroup/geaflow/dsl/connector/jdbc/util/JDBCUtils.java
- geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-jdbc/src/test/java/com/antgroup/geaflow/dsl/connector/jdbc/JDBCTableConnectorTest.java
- geaflow/geaflow-dsl/geaflow-dsl-runtime/src/test/resources/query/jdbc_write_001.sql
Bug fix for JDBC SQL insert in file JDBCUtils.
> [ISSUE-176] bug fix for jdbc sql insert

- geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-kafka/src/main/java/com/antgroup/geaflow/dsl/connector/kafka/KafkaConfigKeys.java
- geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-kafka/src/main/java/com/antgroup/geaflow/dsl/connector/kafka/KafkaTableSink.java
- geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-kafka/src/main/java/com/antgroup/geaflow/dsl/connector/kafka/KafkaTableSource.java
- geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-kafka/src/main/java/com/antgroup/geaflow/dsl/connector/kafka/utils/KafkaConstants.java
Create KakfaProducer and KafkaConsumer with client.id
> [ISSUE-500] [DSL] Create KakfaProducer and KafkaConsumer with client.id

- geaflow/geaflow-common/src/main/java/com/antgroup/geaflow/common/config/keys/ExecutionConfigKeys.java
- geaflow/geaflow-core/geaflow-engine/geaflow-shuffle/pom.xml
- geaflow/geaflow-core/geaflow-engine/geaflow-shuffle/src/main/java/com/antgroup/geaflow/shuffle/api/writer/ShardWriter.java
- geaflow/geaflow-core/geaflow-engine/geaflow-shuffle/src/main/java/com/antgroup/geaflow/shuffle/network/protocol/MemoryViewFileRegion.java
- geaflow/geaflow-core/geaflow-engine/geaflow-shuffle/src/main/java/com/antgroup/geaflow/shuffle/pipeline/buffer/MemoryViewBuffer.java
- geaflow/geaflow-core/geaflow-engine/geaflow-shuffle/src/main/java/com/antgroup/geaflow/shuffle/pipeline/buffer/ShuffleMemoryTracker.java
- geaflow/geaflow-core/geaflow-engine/geaflow-shuffle/src/test/java/com/antgroup/geaflow/shuffle/network/netty/SliceRequestClientTest.java
- geaflow/geaflow-core/geaflow-engine/geaflow-shuffle/src/test/java/com/antgroup/geaflow/shuffle/pipeline/buffer/MemoryViewBufferTest.java
- geaflow/geaflow-core/geaflow-engine/geaflow-shuffle/src/test/java/com/antgroup/geaflow/shuffle/pipeline/buffer/ShuffleMemoryTrackerTest.java
- geaflow/geaflow-examples/src/test/java/com/antgroup/geaflow/example/graph/GraphAlgorithmsTest.java
- geaflow/pom.xml
Integration shuffle with memory pool manager, which allocate shuffle buffer with direct memory, instead of heap memory.
> [ISSUE-511] enable shuffle memory pool

- geaflow/geaflow-plugins/geaflow-store/geaflow-store-paimon/src/main/java/com/antgroup/geaflow/store/paimon/BasePaimonStore.java
- geaflow/geaflow-plugins/geaflow-store/geaflow-store-paimon/src/test/java/com/antgroup/geaflow/store/paimon/PaimonRWHandleTest.java
- geaflow/geaflow-state/geaflow-state-impl/src/test/java/com/antgroup/geaflow/state/jmh/StaticGraphStateWriteJMH10.java
This is part of the code that supports the Paimon job graph data format State, used to replace the previous KV-based Paimon Table.
> [STORE]Add paimon graph table handle.

- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/fetcher/PipelineInputFetcher.java
- geaflow/geaflow-core/geaflow-engine/geaflow-shuffle/src/main/java/com/antgroup/geaflow/shuffle/api/reader/PipelineReader.java
- geaflow/geaflow-core/geaflow-engine/geaflow-shuffle/src/main/java/com/antgroup/geaflow/shuffle/pipeline/fetcher/MultiShardFetcher.java
> [ISSUE-513] fix shuffle fetcher thread leak

- geaflow/geaflow-plugins/geaflow-store/geaflow-store-paimon/pom.xml
- geaflow/geaflow-plugins/geaflow-store/geaflow-store-paimon/src/main/java/com/antgroup/geaflow/store/paimon/KVPaimonStore.java
- geaflow/geaflow-plugins/geaflow-store/geaflow-store-paimon/src/main/java/com/antgroup/geaflow/store/paimon/PaimonTableRWHandle.java
- geaflow/geaflow-plugins/geaflow-store/geaflow-store-paimon/src/main/java/com/antgroup/geaflow/store/paimon/predicate/BytesStartsWith.java
- geaflow/geaflow-plugins/geaflow-store/geaflow-store-paimon/src/main/java/com/antgroup/geaflow/store/paimon/proxy/PaimonBaseGraphProxy.java
- geaflow/geaflow-plugins/geaflow-store/geaflow-store-paimon/src/main/java/com/antgroup/geaflow/store/paimon/proxy/PaimonGraphRWProxy.java
- geaflow/geaflow-plugins/geaflow-store/geaflow-store-paimon/src/test/java/com/antgroup/geaflow/store/paimon/PaimonRWHandleTest.java
- geaflow/geaflow-plugins/geaflow-store/geaflow-store-paimon/src/test/java/com/antgroup/geaflow/store/paimon/predicate/BytesStartsWithTest.java
- geaflow/geaflow-state/geaflow-state-impl/src/test/java/com/antgroup/geaflow/state/PaimonGraphStateTest.java
- geaflow/geaflow-state/geaflow-state-impl/src/test/java/com/antgroup/geaflow/state/PaimonKeyStateTest.java
Support key pushdown in paimon store.
- [✅] Tests have Added for the changes
> [ISSUE-518] Support key pushdown in paimon store.

- geaflow/geaflow-plugins/geaflow-store/geaflow-store-rocksdb/src/main/java/com/antgroup/geaflow/store/rocksdb/RocksdbConfigKeys.java
- geaflow/geaflow-plugins/geaflow-store/geaflow-store-rocksdb/src/main/java/com/antgroup/geaflow/store/rocksdb/proxy/ProxyBuilder.java
- geaflow/geaflow-plugins/geaflow-store/geaflow-store-rocksdb/src/main/java/com/antgroup/geaflow/store/rocksdb/proxy/SyncGraphDtPartitionProxy.java
- geaflow/geaflow-state/geaflow-state-common/src/main/java/com/antgroup/geaflow/state/pushdown/filter/inner/FilterHelper.java
- geaflow/geaflow-state/geaflow-state-common/src/test/java/com/antgroup/geaflow/state/filter/StateFilterTest.java
- geaflow/geaflow-state/geaflow-state-impl/src/test/java/com/antgroup/geaflow/state/RocksDBDtPartitionGraphStateTest.java
Support vertex and edge being partitioned by timestamp
- [✅] Tests have Added for the changes
> [State] Support vertex and edge being partitioned by timestamp

- geaflow/geaflow-dsl/geaflow-dsl-plan/src/main/java/com/antgroup/geaflow/dsl/schema/function/BuildInSqlFunctionTable.java
- geaflow/geaflow-dsl/geaflow-dsl-plan/src/main/java/com/antgroup/geaflow/dsl/udf/table/array/ArrayAppend.java
- geaflow/geaflow-dsl/geaflow-dsl-plan/src/main/java/com/antgroup/geaflow/dsl/udf/table/array/ArrayContains.java
- geaflow/geaflow-dsl/geaflow-dsl-plan/src/main/java/com/antgroup/geaflow/dsl/udf/table/array/ArrayDistinct.java
- geaflow/geaflow-dsl/geaflow-dsl-plan/src/main/java/com/antgroup/geaflow/dsl/udf/table/array/ArrayUnion.java
- geaflow/geaflow-dsl/geaflow-dsl-plan/src/test/java/com/antgroup/geaflow/dsl/udf/array/ArrayTest.java
Support array operation function.
> [ISSUE-538] Support array function

- geaflow-mcp/pom.xml
- geaflow-mcp/src/main/java/com/antgroup/geaflow/mcp/server/GeaFlowMcpServer.java
- geaflow-mcp/src/main/java/com/antgroup/geaflow/mcp/server/GeaFlowMcpServerTools.java
- geaflow-mcp/src/main/java/com/antgroup/geaflow/mcp/util/YamlParser.java
- geaflow-mcp/src/main/resources/app.yml
- geaflow-mcp/src/main/resources/log4j.properties
- geaflow-mcp/src/test/java/com/antgroup/geaflow/mcp/server/GeaFlowMcpClientTest.java
- geaflow-mcp/src/test/java/com/antgroup/geaflow/mcp/server/util/YamlParserTest.java
- geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/com/antgroup/geaflow/cluster/client/GeaFlowClient.java
- geaflow/geaflow-deploy/geaflow-on-local/src/main/java/com/antgroup/geaflow/cluster/local/client/LocalClusterClient.java
- pom.xml
- [ ✅] Tests have Added for the changes
> support geaflow mcp server and provide basic query service

- geaflow/geaflow-plugins/geaflow-store/geaflow-store-paimon/src/main/java/com/antgroup/geaflow/store/paimon/BasePaimonStore.java
- geaflow/geaflow-plugins/geaflow-store/geaflow-store-paimon/src/main/java/com/antgroup/geaflow/store/paimon/DynamicGraphPaimonStoreBase.java
- geaflow/geaflow-plugins/geaflow-store/geaflow-store-paimon/src/main/java/com/antgroup/geaflow/store/paimon/KVPaimonStore.java
- geaflow/geaflow-plugins/geaflow-store/geaflow-store-paimon/src/main/java/com/antgroup/geaflow/store/paimon/PaimonStoreBuilder.java
- geaflow/geaflow-plugins/geaflow-store/geaflow-store-paimon/src/main/java/com/antgroup/geaflow/store/paimon/StaticGraphPaimonStoreBase.java
- geaflow/geaflow-plugins/geaflow-store/geaflow-store-paimon/src/main/java/com/antgroup/geaflow/store/paimon/proxy/IGraphMultiVersionedPaimonProxy.java
- geaflow/geaflow-plugins/geaflow-store/geaflow-store-paimon/src/main/java/com/antgroup/geaflow/store/paimon/proxy/PaimonGraphMultiVersionedProxy.java
- geaflow/geaflow-plugins/geaflow-store/geaflow-store-paimon/src/main/java/com/antgroup/geaflow/store/paimon/proxy/PaimonProxyBuilder.java
- geaflow/geaflow-state/geaflow-state-impl/src/test/java/com/antgroup/geaflow/state/PaimonDynamicGraphStateTest.java
- geaflow/geaflow-state/geaflow-state-impl/src/test/java/com/antgroup/geaflow/state/PaimonGraphStateTest.java
- [✅] Tests have Added for the changes
> [ISSUE-553] Support dynamic graph APIs in Paimon store.

- CODE_OF_CONDUCT.md
> fix: change the contact email to dev@geaflow.apache.org

- geaflow/geaflow-state/geaflow-state-common/src/main/resources/Filter.template
Fix invalid Filter.template issue
> Fix invalid Filter.template issue

- GOVERNANCE.md
- community/CONTRIBUTING.md
- community/MEETING.md
- community/ROLES.md
- Revise CONTRIBUTING.md with detailed steps and prerequisites
- Add MEETING.md for bi-weekly community meeting details
- Update ROLES.md with structured role descriptions
- Introduce GOVERNANCE.md for project governance overview
#579
> docs: update contributing guidelines and add governance docs 📚

- community/CONTRIBUTING.md
- community/ROLES.md
- Simplify CONTRIBUTING.md with concise steps and prerequisites
- Restructure ROLES.md for clarity and remove redundant content
- Update community links and resources for consistency
> docs: streamline contributing and roles documentation 📚

- geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-api/src/main/java/org/apache/geaflow/dsl/connector/api/FetchData.java
- geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-hive/src/main/java/org/apache/geaflow/dsl/connector/hive/HiveReader.java
- geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-hive/src/main/java/org/apache/geaflow/dsl/connector/hive/HiveTableSource.java
- geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-hive/src/test/java/org/apache/geaflow/dsl/connector/hive/HiveTableSourceTest.java
- geaflow/geaflow-dsl/geaflow-dsl-runtime/src/test/java/org/apache/geaflow/dsl/runtime/query/HiveSourceTest.java
- geaflow/geaflow-dsl/geaflow-dsl-runtime/src/test/resources/query/hive_source_001.sql
What changes were proposed in this pull request?
Add streaming source for hive
resolve #592
> [ISSUE-592] feat: Add a Streaming Source for Hiveadd stream hive reader
